"""Speech-to-text transcription module."""

from ai_knowledge_pipeline.modules.transcription.contracts import (
    DefaultTranscriber,
    ProviderTranscriptionResult,
    SpeakerMetadata,
    Transcriber,
    TranscriptArtifact,
    TranscriptFormat,
    TranscriptSegment,
    TranscriptTimestamp,
    TranscriptionConfig,
    TranscriptionErrorCode,
    TranscriptionIssue,
    TranscriptionIssueSeverity,
    TranscriptionProvider,
    TranscriptionProviderKind,
    TranscriptionRequest,
    TranscriptionResult,
    TranscriptionStatus,
    UnavailableTranscriptionProvider,
    create_default_transcriber,
)

__all__ = [
    "DefaultTranscriber",
    "ProviderTranscriptionResult",
    "SpeakerMetadata",
    "Transcriber",
    "TranscriptArtifact",
    "TranscriptFormat",
    "TranscriptSegment",
    "TranscriptTimestamp",
    "TranscriptionConfig",
    "TranscriptionErrorCode",
    "TranscriptionIssue",
    "TranscriptionIssueSeverity",
    "TranscriptionProvider",
    "TranscriptionProviderKind",
    "TranscriptionRequest",
    "TranscriptionResult",
    "TranscriptionStatus",
    "UnavailableTranscriptionProvider",
    "create_default_transcriber",
]
